### ISSUE TITLE
problem of "Context was terminated"

### ISSUE THREAD

**Issue by LiXi-storage** [DDNStorage/clownfish#3]
The context of zmq shouldn't be shared by multiple threads.

[2019/04/02-23:00:04] [None] [INFO] [clownfish_test.py:1009] test [abort_command] passed
[2019/04/02-23:00:04] [None] [INFO] [clownfish_test.py:1009] test [prepare_twice] passed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/log/ltest_launch/2019-04-02-22_26_41/clownfish_build_log/pyclownfish/clownfish_console.py", line 195, in cc_ping_thread
    CLOWNFISH_CONSOLE_PING_TIMEOUT)
  File "/var/log/ltest_launch/2019-04-02-22_26_41/clownfish_build_log/pyclownfish/clownfish_console.py", line 79, in ccm_communicate
    events = dict(poll.poll(CLOWNFISH_CONSOLE_POLL_TIMEOUT * 1000))
  File "/usr/lib64/python2.7/site-packages/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1631)
  File "checkrc.pxd", line 18, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1951)
ContextTerminated: Context was terminated

[2019/04/02-23:00:04] [None] [INFO] [clownfish_test.py:1253] test of Clownfish passed, please check [/var/log/ltest_launch/2019-04-02-22_26_41/clownfish_test] for more log
[2019/04/02-23:00:04] [filelock] [INFO] [filelock.py:318] Lock 140246959585872 released on /var/log/ltest_launch/2019-04-02-22_26_41/clownfish_test.conf.lock
[2019/04/02-23:00:05] [None] [INFO] [ssh_host.py:2314] got directory [/var/log/ltest_launch/2019-04-02-22_26_41/clownfish_test] on host [ime02] to directory [/var/log/ltest_launch/2019-04-02-22_26_41/ime02] on localhost
[2019/04/02-23:00:16] [None] [INFO] [ssh_host.py:2314] got directory [/var/log/ltest_launch/2019-04-02-22_26_41/clownfish_build_log] on host [ime02] to directory [/var/log/ltest_launch/2019-04-02-22_26_41/ime02] on localhost
[2019/04/02-23:00:17] [None] [INFO] [ltest_launch.py:1554] released job [2019-04-02-22_26_41-25]
[2019/04/02-23:00:17] [None] [INFO] [ltest_launch.py:1639] successfully launched the test
[2019/04/02-23:00:17] [None] [INFO] [ltest_launch.py:1641] moving the log from [/var/log/ltest_launch/2019-04-02-22_26_41] to [/root/lixi/clownfish/clownfish.git]

**Comment by LiXi-storage** [comment]
Fixed by https://github.com/DDNStorage/clownfish/commit/144ff795a61738a3809988a9ff5750acca4a1700
